name: "CI Trigger: PR"

on:
  pull_request:
    paths:
      - ".github/actions/**"
      - ".github/workflows/**"
      - "src/**/*"
      - ".nvmrc"
      - "*.js"
      - "*.json"
      - "*.ts"
      - "*.yaml"

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml
