name: "'node-utils' Test (main)"

on:
  push:
    branches:
      - main
    paths:
      - ".github/actions/**"
      - ".github/workflows/**"
      - "src/**/*"
      - ".nvmrc"
      - "*.js"
      - "*.json"
      - "*.ts"
      - "*.yaml"

jobs:
  test:
    runs-on: [ubuntu-latest]
    timeout-minutes: 15
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: "Set up Node version and dependencies"
        uses: ./.github/actions/package-setup

      - name: "🖊️ Run tests"
        run: pnpm test:cov
